{{- if .Values.gateway.enabled -}}
{{- $fullname := (include "trino.fullname" .) -}}
{{- $coordinatorName := (include "trino.coordinator" .) -}}

apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $coordinatorName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "trino.labels" . | nindent 4 }}
    component: trino-httproute
  {{- with .Values.gateway.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.gateway.parentRefs }}
  parentRefs:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  {{- with .Values.gateway.hostnames }}
  hostnames:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.gateway.rules }}
    - matches:
        {{- if .matches }}
        {{- toYaml .matches | nindent 8 }}
        {{- else }}
        - path:
            type: {{ .path.type | default "PathPrefix" }}
            value: {{ .path.value | default "/" }}
        {{- end }}
      {{- if .filters }}
      filters:
        {{- toYaml .filters | nindent 8 }}
      {{- end }}
      backendRefs:
        - name: {{ $fullname }}
          
          port: {{ if $.Values.server.config.https.enabled }}{{ $.Values.server.config.https.port }}{{ else }}{{ $.Values.service.port }}{{ end }}
          {{- if .weight }}
          weight: {{ .weight }}
          {{- end }}
    {{- end }}


{{- if .Values.gateway.redirectRoute.enabled -}}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $coordinatorName }}-redirect
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "trino.labels" . | nindent 4 }}
    component: trino-httproute-redirect
spec:
  {{- with .Values.gateway.redirectRoute.parentRefs }}
  parentRefs:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  {{- with .Values.gateway.hostnames }}
  hostnames:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        statusCode: 301
{{- end }}


{{- if .Values.gateway.backendTLSPolicy.enabled -}}
---
apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: {{ $coordinatorName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "trino.labels" . | nindent 4 }}
spec:
  targetRefs:
  - group: gateway.networking.k8s.io/v1
    kind: Service
    name: {{ $fullname }}
  validation:
    {{- if .Values.gateway.backendTLSPolicy.hostname }}
    hostname: {{ tpl .Values.gateway.backendTLSPolicy.hostname $ | quote }}
    {{- else }}
    hostname: {{ printf "%s.%s.svc.cluster.local" $fullname .Release.Namespace | quote }}
    {{- end }}
    {{- if .Values.gateway.backendTLSPolicy.caCertificateRefs }}
    caCertificateRefs:
    {{- toYaml .Values.gateway.backendTLSPolicy.caCertificateRefs | nindent 6 }}
    {{- end }}
{{- end }}
{{- end }}