{{- /* Qubership custom change: dynamic catalog support */ -}}
{{- if and .Values.dynamicCatalog.enabled (eq .Values.dynamicCatalog.store "file") (not .Values.dynamicCatalog.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "trino.fullname" . }}-dynamic-catalog
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "trino.labels" . | nindent 4 }}
    app.kubernetes.io/component: coordinator
spec:
  accessModes:
    - {{ .Values.dynamicCatalog.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.dynamicCatalog.persistence.size }}
  {{- if .Values.dynamicCatalog.persistence.storageClass }}
  storageClassName: {{ .Values.dynamicCatalog.persistence.storageClass }}
  {{- end }}
{{- end }}
