{{- if and .Values.server.config.https.enabled .Values.tls.enabled }}
{{- if not .Values.tls.generateCerts.enabled }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.tls.secretMounts.secretName }}
  namespace: {{ .Release.Namespace }}
data:
  {{- if .Values.tls.certificates.tls }}
  tls-combined.pem: {{ .Values.tls.certificates.tls | quote }}
  {{- end }}
{{- end }}
{{- end }}
