{{- if or .Values.catalogs .Values.additionalCatalogs }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "trino.catalog" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "trino.labels" . | nindent 4 }}
stringData:
  {{- $merged := merge .Values.catalogs .Values.additionalCatalogs }}
  {{- range $catalogName, $catalogProperties := $merged }}
  {{ $catalogName }}.properties: |
    {{ tpl $catalogProperties $ | nindent 4 }}
  {{- end }}
{{- end }}


