{{- if and .Values.tls.enabled .Values.tls.generateCerts.enabled }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: trino-tls-issuer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "trino.labels" . | nindent 4 }}
    {{- include "cert_manager_label" . | nindent 4 }}
spec:
  selfSigned: {}
{{- end }}
